meta:
  nextgen: true
  
notifications:
  commits:              commits@infra.apache.org
  pullrequests:         commits@infra.apache.org
  issues:               commits@infra.apache.org
  jobs:                 commits@infra.apache.org
  discussions:          users@infra.apache.org

