meta:
  nextgen: true
  
notifications:
  commits:              commits@infra.apache.org
  pullrequests:         commits@infra.apache.org
  issues:               users@infra.apache.org
  jobs:                 commits@infra.apache.org
  discussions:          commits@infra.apache.org
